#!/usr/bin/env python3
"""Layer-by-layer table behind the CV plot: |mean| dose, sd (spread), CV.

The CV figure alone can mislead — CV falls with depth not because the résumé-to-
résumé spread shrinks (it GROWS) but because the mean bias grows even faster, and
the tall early CV is a small-denominator artifact (mean ~ 0). This table makes the
mean/sd/CV decomposition explicit. Averages the per-layer profile over experiments;
reconstructs sd = CV * |mean|.

    python scripts/make_cv_table.py runs/erosion_resume_mistral7b_34711*/erosion_comparison.json \
        --out docs/cv_table.tex
"""
import argparse, glob, json
from pathlib import Path
import numpy as np


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("json", nargs="+")
    ap.add_argument("--out", default="docs/cv_table.tex")
    args = ap.parse_args(argv)

    means, cvs, L = [], [], None
    for f in args.json:
        p = json.loads(Path(f).read_text())["candidate"]["layer_variance_profile"]
        means.append(p["per_layer_proj_mean"]); cvs.append(p["per_layer_proj_cv"]); L = p["layer_index"]
    n = len(means)
    mean = np.abs(np.array(means)).mean(0)      # |mean| dose per layer
    cv = np.array(cvs).mean(0)                   # CV per layer
    sd = cv * mean                               # sd = CV * |mean|

    half = (len(L) + 1) // 2
    left, right = range(0, half), range(half, len(L))
    nl = "\n"
    eol = r" \\"
    body = nl.join(
        f"    {L[l]} & {mean[l]:.3f} & {sd[l]:.3f} & {cv[l]:.2f} & "
        f"{L[r]} & {mean[r]:.3f} & {sd[r]:.3f} & {cv[r]:.2f}" + eol
        for l, r in zip(left, right)
    )

    tex = rf"""% Auto-generated by scripts/make_cv_table.py  (mean over {n} experiments)
\begin{{table}}[t]
  \centering
  \small
  \caption{{Layer-by-layer decomposition of the projection coefficient of variation
  (mean over {n} experiments). The per-résumé bias ``dose'' is $s_i=\langle\delta_i,\bar d\rangle$;
  $|\bar s|$ is its mean, sd its spread, and $\mathrm{{CV}}=\mathrm{{sd}}/|\bar s|$. Both the mean
  dose and the spread grow by two orders of magnitude with depth; CV falls only because the
  mean grows faster, and the large early CV reflects a near-zero denominator (little bias yet),
  not high absolute variability.}}
  \label{{tab:cv-decomposition}}
  \begin{{tabular}}{{rrrr@{{\hskip 2em}}rrrr}}
    \toprule
    Layer & $|\bar s|$ & sd & CV & Layer & $|\bar s|$ & sd & CV \\
    \midrule
{body}
    \bottomrule
  \end{{tabular}}
\end{{table}}
"""
    outp = Path(args.out); outp.parent.mkdir(parents=True, exist_ok=True)
    outp.write_text(tex)
    print(tex)
    print(f"[cv-table] wrote {outp}  ({n} experiments)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
