#!/usr/bin/env python3
"""Prompt-selection table: per-template real gap, placebo gap, and performance.

Surfaces the placebo control so its role is visible: R2 accepts a prompt only if the
real (White-vs-Black) gap is small AND within tolerance of the placebo (White-vs-White')
gap; R3 then picks the eligible prompt with the highest balanced accuracy. On the base
model all templates are demographically neutral, so the placebo confirms neutrality
rather than discriminating; selection is driven by balanced accuracy.

    python scripts/make_prompt_table.py runs/prompt_selection_mistral7b_3466340/prompt_selection.json \
        --out docs/prompt_table.tex
"""
import argparse, json
from pathlib import Path


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("json")
    ap.add_argument("--out", default="docs/prompt_table.tex")
    ap.add_argument("--tau", type=float, default=0.05)
    args = ap.parse_args(argv)

    d = json.loads(Path(args.json).read_text())
    winner = d.get("winner")
    rows = sorted(d["rows"], key=lambda r: (not r.get("eligible", False), -(r.get("balanced_acc") or 0)))

    def esc(s):  # LaTeX-safe underscores
        return str(s).replace("_", r"\_")

    body = []
    for r in rows:
        ba = r.get("balanced_acc")
        ba = f"{ba:.3f}" if ba is not None else "--"
        elig = r"\checkmark" if r.get("eligible") else r"$\times$"
        name = esc(r["prompt"]) + (r"\,$\star$" if r["prompt"] == winner else "")
        body.append(
            f"    {name} & {'Y' if r['has_jd'] else 'N'} & "
            f"{r['real_gap']:+.3f} & {r['placebo_gap']:+.3f} & {ba} & {elig} \\\\"
        )
    body = "\n".join(body)

    tex = rf"""% Auto-generated by scripts/make_prompt_table.py
\begin{{table}}[t]
  \centering\small
  \caption{{Pre-registered prompt selection on the base model. \emph{{Real gap}}
  $\Delta_{{\mathrm{{real}}}}$ is the White-vs-Black change in $P(\text{{Yes}})$;
  \emph{{placebo gap}} $\Delta_{{\mathrm{{plac}}}}$ is the White-vs-White$'$ control.
  A prompt is eligible (R1--R2) if it includes the job description and is
  demographically neutral ($\Delta_{{\mathrm{{real}}}}\le\tau$ and
  $|\Delta_{{\mathrm{{real}}}}-\Delta_{{\mathrm{{plac}}}}|\le\tau$, $\tau={args.tau}$);
  the winner ($\star$) is the eligible prompt with the highest balanced accuracy (R3).
  All templates are demographically neutral (real $\approx$ placebo $\approx 0$), so the
  placebo confirms neutrality and selection is driven by balanced accuracy.}}
  \label{{tab:prompt-selection}}
  \begin{{tabular}}{{lccccc}}
    \toprule
    Prompt & JD & $\Delta_{{\mathrm{{real}}}}$ & $\Delta_{{\mathrm{{plac}}}}$ & Bal.\ Acc & Elig. \\
    \midrule
{body}
    \bottomrule
  \end{{tabular}}
\end{{table}}
"""
    outp = Path(args.out); outp.parent.mkdir(parents=True, exist_ok=True)
    outp.write_text(tex)
    print(tex)
    print(f"[prompt-table] wrote {outp}  (winner {winner})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
