#!/usr/bin/env python3
"""Layer-selection table: per-layer alignment and strength behind the chosen layer.

Bias identification picks the layer that maximises alignment * strength:
  * alignment = |cos(v_demo, v_guard)| -- the demographic direction (white-black
    difference-of-means) aligned with the guardrail/injection direction (M_b - B);
  * strength  = ||d_l|| / ||h_l|| -- the bias differential relative to the residual norm.
The Activation-Differentials figure already shows strength; alignment is not plotted
anywhere (the layer-profile cosine panel is the *per-pair* cosine, a different quantity).
This table exposes both so the chosen layer is justified. Averages over experiments.

    python scripts/make_selection_table.py runs/erosion_resume_mistral7b_34711*/erosion_comparison.json \
        --out docs/selection_table.tex
"""
import argparse, json
from pathlib import Path
import numpy as np


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("json", nargs="+")
    ap.add_argument("--out", default="docs/selection_table.tex")
    args = ap.parse_args(argv)

    align, strength, chosen, L = [], [], [], None
    for f in args.json:
        c = json.loads(Path(f).read_text())["candidate"]
        align.append(c["per_layer_alignment"])
        strength.append(c["layer_variance_profile"]["per_layer_strength_rel"])
        chosen.append((c.get("layers") or [None])[0])
        L = c["layer_variance_profile"]["layer_index"]
    n = len(align)
    align = np.array(align).mean(0)
    strength = np.array(strength).mean(0)
    ch = float(np.mean([x for x in chosen if x is not None]))

    half = (len(L) + 1) // 2
    eol = r" \\"
    body = "\n".join(
        f"    {L[l]} & {align[l]:.3f} & {strength[l]:.3f} & "
        f"{L[r]} & {align[r]:.3f} & {strength[r]:.3f}" + eol
        for l, r in zip(range(0, half), range(half, len(L)))
    )

    tex = rf"""% Auto-generated by scripts/make_selection_table.py  (mean over {n} experiments)
\begin{{table}}[t]
  \centering
  \small
  \caption{{Layer-selection evidence (mean over {n} experiments). \emph{{Alignment}} is
  $|\cos(v_\mathrm{{bias}}, v_\mathrm{{demo}})|$, the cosine between the bias direction
  $v_\mathrm{{bias}}$ (the difference-in-differences $(M_b^{{\mathrm{{W}}}}{{-}}M_b^{{\mathrm{{B}}}}){{-}}(B^{{\mathrm{{W}}}}{{-}}B^{{\mathrm{{B}}}})$)
  and the demographic direction $v_\mathrm{{demo}}$ (the White$-$Black difference-of-means in $M_b$);
  \emph{{strength}} is $\|d_\ell\|/\|h_\ell\|$, the bias differential relative to the residual norm.
  Bias identification selects the layer maximising alignment~$\times$~strength; both peak in the
  final layers (mean chosen layer $\approx$ {ch:.0f}).}}
  \label{{tab:layer-selection}}
  \begin{{tabular}}{{rrr@{{\hskip 2em}}rrr}}
    \toprule
    Layer & Alignment & Strength & Layer & Alignment & Strength \\
    \midrule
{body}
    \bottomrule
  \end{{tabular}}
\end{{table}}
"""
    outp = Path(args.out); outp.parent.mkdir(parents=True, exist_ok=True)
    outp.write_text(tex)
    print(tex)
    print(f"[selection-table] wrote {outp}  ({n} experiments; alignment max L{L[int(np.argmax(align))]} "
          f"{align.max():.3f}; strength max L{L[int(np.argmax(strength))]} {strength.max():.3f})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
